# SPDX-FileCopyrightText: 2023 Nikita Chernyi
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform echoip installation tasks
  when: echoip_enabled | bool
  tags:
    - setup-all
    - setup-echoip
    - install-all
    - install-echoip
  block:
    - name: Validate echoip configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install echoip
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform echoip uninstallation tasks
  when: not echoip_enabled | bool
  tags:
    - setup-all
    - setup-echoip
  block:
    - name: Uninstall echoip
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
